version: 2
jobs:
  build:  
    docker:
      - image: circleci/node:11
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: yarn test
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y python3-pip
            pip3 install awscli
            curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - run:
          name: Install doctl
          command: |
            wget https://github.com/digitalocean/doctl/releases/download/v1.64.0/doctl-1.64.0-linux-amd64.tar.gz
            tar xf doctl-1.64.0-linux-amd64.tar.gz
            sudo mv doctl /usr/local/bin
            rm doctl-1.64.0-linux-amd64.tar.gz
      - run:
          name: Authenticate with DigitalOcean
          command: |
            doctl auth init --access-token $OCEAN_API_KEY
            doctl kubernetes cluster kubeconfig save mycluster
            kubectl config use-context do-myapp
      - run:
          name: Deploy to DigitalOcean
          command: |
            kubectl apply -f k8s

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main